import { BusinessPath } from "./types.js";

export const businessPaths: BusinessPath[] = [
  {
    id: "content-creation",
    name: "Content Creation / UGC",
    description:
      "Create videos, photos, blogs, or social media posts for personal brands or other businesses",
    detailedDescription:
      "Content creation and user-generated content (UGC) involve producing videos, photos, blogs, or social media posts for personal brands or other businesses. UGC creators are often paid by companies to create native-style content that aligns with the brand's identity but feels organic to viewers.",
    fitScore: 0,
    difficulty: "Easy",
    timeToProfit: "2-4 weeks",
    startupCost: "$0-300",
    potentialIncome: "$0-20K/month",
    pros: [
      "Extremely low barrier to entry",
      "Creative freedom and self-expression",
      "Potential for large income with no inventory",
      "Flexible work schedule",
      "Builds long-term personal brand equity",
      "Opens opportunities in many niches",
    ],
    cons: [
      "Algorithms can change rapidly",
      "Time-intensive content planning and editing",
      "Emotional toll of public feedback",
      "Inconsistent income early on",
      "High competition and saturation",
      "Burnout is common without balance",
    ],
    tools: ["CapCut", "Canva", "TikTok", "Instagram", "Notion"],
    skills: [
      "Creative thinking",
      "Communication",
      "Social media",
      "Visual storytelling",
      "Trend awareness",
    ],
    icon: "TrendingUp",
    marketSize: "Creator economy valued at over $104B",
    averageIncome: {
      beginner: "$0-500/month",
      intermediate: "$500-5K/month",
      advanced: "$5K-20K/month",
    },
    userStruggles: [
      "Consistency challenges",
      "Audience growth",
      "Monetization timing",
      "Negative feedback handling",
    ],
    solutions: [
      "Content calendar planning",
      "Focus on niche audience",
      "Diversify revenue streams",
      "Build thick skin and community",
    ],
    bestFitPersonality: [
      "Creative and innovative",
      "Patient and persistent",
      "Comfortable on camera",
      "Resilient to criticism",
    ],
    resources: {
      platforms: ["YouTube", "TikTok", "Instagram", "Creator Now"],
      learning: ["YouTube Creator Academy", "Creator economy courses"],
      tools: ["CapCut", "Canva", "Later", "Notion"],
    },
    actionPlan: {
      phase1: [
        "Choose content niche",
        "Set up equipment",
        "Create content calendar",
        "Post consistently",
      ],
      phase2: [
        "Engage with audience",
        "Collaborate with others",
        "Optimize for algorithms",
        "Track analytics",
      ],
      phase3: [
        "Monetize through ads",
        "Secure sponsorships",
        "Launch own products",
        "Expand to new platforms",
      ],
    },
  },
  {
    id: "freelancing",
    name: "Freelancing",
    description:
      "Offer specialized services to clients on a project or contract basis",
    detailedDescription:
      "Freelancing involves offering specialized services to clients on a project or contract basis. This could include writing, graphic design, web development, marketing, consulting, or any skill-based service. Freelancers work independently, often with multiple clients, and have the flexibility to choose their projects and set their rates.",
    fitScore: 0,
    difficulty: "Easy",
    timeToProfit: "1-2 weeks",
    startupCost: "$0-500",
    potentialIncome: "$1K-15K+/month",
    pros: [
      "Quick to start with existing skills",
      "Complete schedule flexibility",
      "Choose your own clients and projects",
      "No inventory or upfront costs",
      "Can work from anywhere",
      "Direct relationship with income and effort",
    ],
    cons: [
      "Income can be inconsistent",
      "No benefits or job security",
      "Constant client acquisition needed",
      "Time-for-money limitation",
      "Handling all business aspects alone",
      "Potential for scope creep and difficult clients",
    ],
    tools: ["Upwork", "Fiverr", "LinkedIn", "Slack", "Zoom"],
    skills: [
      "Specialized expertise",
      "Client communication",
      "Project management",
      "Time management",
      "Networking",
    ],
    icon: "Briefcase",
    marketSize: "Freelance economy worth $400B+ globally",
    averageIncome: {
      beginner: "$500-2K/month",
      intermediate: "$2K-8K/month",
      advanced: "$8K-15K+/month",
    },
    userStruggles: [
      "Finding consistent clients",
      "Pricing services appropriately",
      "Managing multiple projects",
      "Dealing with difficult clients",
    ],
    solutions: [
      "Build strong portfolio and testimonials",
      "Develop recurring client relationships",
      "Use project management tools",
      "Set clear boundaries and contracts",
    ],
    bestFitPersonality: [
      "Self-motivated and disciplined",
      "Strong communication skills",
      "Adaptable to different clients",
      "Business-minded",
    ],
    resources: {
      platforms: ["Upwork", "Fiverr", "LinkedIn", "Freelancer"],
      learning: ["Freelancer courses", "Industry certifications"],
      tools: ["Slack", "Zoom", "Trello", "FreshBooks"],
    },
    actionPlan: {
      phase1: [
        "Identify your skills",
        "Create portfolio",
        "Set up profiles on platforms",
        "Apply for first projects",
      ],
      phase2: [
        "Deliver quality work",
        "Collect testimonials",
        "Raise your rates",
        "Build repeat clients",
      ],
      phase3: [
        "Specialize in high-value niches",
        "Create passive income streams",
        "Build a personal brand",
        "Consider hiring subcontractors",
      ],
    },
  },
  // Add more business paths as needed
  {
    id: "affiliate-marketing",
    name: "Affiliate Marketing",
    description:
      "Promote other companies' products and earn commissions on successful referrals",
    detailedDescription:
      "Affiliate marketing involves promoting other companies' products or services and earning a commission for each sale or lead generated through your referral. This can be done through blogs, social media, email marketing, or paid advertising.",
    fitScore: 0,
    difficulty: "Medium",
    timeToProfit: "3-6 months",
    startupCost: "$0-1000",
    potentialIncome: "$0-50K+/month",
    pros: [
      "No product creation required",
      "Passive income potential",
      "Low startup costs",
      "Flexible schedule",
      "Scalable income",
      "Work from anywhere",
    ],
    cons: [
      "Takes time to build audience",
      "Dependent on other companies",
      "Commission-based income",
      "High competition",
      "Need to constantly adapt to changes",
      "Building trust takes time",
    ],
    tools: [
      "WordPress",
      "ConvertKit",
      "Google Analytics",
      "Canva",
      "Social media platforms",
    ],
    skills: [
      "Content creation",
      "SEO",
      "Email marketing",
      "Social media marketing",
      "Analytics",
    ],
    icon: "TrendingUp",
    marketSize: "Affiliate marketing industry worth $17B+ globally",
    averageIncome: {
      beginner: "$0-500/month",
      intermediate: "$500-5K/month",
      advanced: "$5K-50K+/month",
    },
    userStruggles: [
      "Building initial audience",
      "Finding profitable niches",
      "Creating engaging content",
      "Tracking and optimizing campaigns",
    ],
    solutions: [
      "Focus on one niche initially",
      "Provide genuine value first",
      "Use analytics to optimize",
      "Build email list early",
    ],
    bestFitPersonality: [
      "Patient and persistent",
      "Good at building relationships",
      "Analytical mindset",
      "Marketing-oriented",
    ],
    resources: {
      platforms: [
        "Amazon Associates",
        "ShareASale",
        "CJ Affiliate",
        "ClickBank",
      ],
      learning: ["Affiliate marketing courses", "Industry blogs"],
      tools: ["WordPress", "ConvertKit", "Google Analytics", "Canva"],
    },
    actionPlan: {
      phase1: [
        "Choose your niche",
        "Research affiliate programs",
        "Create content platform",
        "Start creating valuable content",
      ],
      phase2: [
        "Build email list",
        "Join affiliate programs",
        "Create product reviews",
        "Optimize for SEO",
      ],
      phase3: [
        "Scale successful campaigns",
        "Diversify income streams",
        "Build personal brand",
        "Consider paid advertising",
      ],
    },
  },
  {
    id: "online-tutoring",
    name: "Online Tutoring",
    description:
      "Teach students online through one-on-one sessions or group classes",
    detailedDescription:
      "Online tutoring involves providing educational services to students through video calls, online platforms, or course creation. This can include academic subjects, language learning, test preparation, or skill-based instruction.",
    fitScore: 0,
    difficulty: "Easy",
    timeToProfit: "1-2 weeks",
    startupCost: "$0-200",
    potentialIncome: "$1K-10K/month",
    pros: [
      "Use existing knowledge and skills",
      "Flexible scheduling",
      "High hourly rates possible",
      "Rewarding work helping others",
      "No inventory needed",
      "Global student reach",
    ],
    cons: [
      "Time-for-money limitation",
      "Seasonal demand variations",
      "Need to manage difficult students",
      "Preparation time required",
      "Competition from platforms",
      "Inconsistent income",
    ],
    tools: ["Zoom", "Google Meet", "Teachable", "Udemy", "Calendly"],
    skills: [
      "Subject expertise",
      "Teaching ability",
      "Patience",
      "Communication",
      "Technology",
    ],
    icon: "BookOpen",
    marketSize: "Online tutoring market worth $15B+ globally",
    averageIncome: {
      beginner: "$500-2K/month",
      intermediate: "$2K-5K/month",
      advanced: "$5K-10K/month",
    },
    userStruggles: [
      "Finding students initially",
      "Setting appropriate rates",
      "Managing scheduling",
      "Handling payment processing",
    ],
    solutions: [
      "Join established platforms first",
      "Create valuable free content",
      "Build student testimonials",
      "Use scheduling tools",
    ],
    bestFitPersonality: [
      "Patient and encouraging",
      "Clear communicator",
      "Subject matter expert",
      "Enjoys helping others",
    ],
    resources: {
      platforms: ["Wyzant", "Tutor.com", "Preply", "iTalki"],
      learning: ["Teaching certification courses", "Online education training"],
      tools: ["Zoom", "Google Meet", "Calendly", "PayPal"],
    },
    actionPlan: {
      phase1: [
        "Define your expertise area",
        "Create tutor profiles",
        "Set competitive rates",
        "Get first students",
      ],
      phase2: [
        "Build reputation and reviews",
        "Increase rates gradually",
        "Develop teaching materials",
        "Expand subject areas",
      ],
      phase3: [
        "Create online courses",
        "Build personal brand",
        "Hire other tutors",
        "Launch tutoring agency",
      ],
    },
  },
  {
    id: "e-commerce",
    name: "E-commerce Store",
    description:
      "Sell physical or digital products online through your own store",
    detailedDescription:
      "E-commerce involves creating an online store to sell products directly to consumers. This can include physical products, digital downloads, print-on-demand items, or dropshipping products from suppliers.",
    fitScore: 0,
    difficulty: "Medium",
    timeToProfit: "2-6 months",
    startupCost: "$500-5K",
    potentialIncome: "$1K-100K+/month",
    pros: [
      "Scalable business model",
      "Passive income potential",
      "Global customer reach",
      "Multiple revenue streams",
      "Build valuable asset",
      "Creative product control",
    ],
    cons: [
      "High initial investment",
      "Inventory management",
      "Customer service demands",
      "Marketing costs",
      "Competition pressure",
      "Technical complexity",
    ],
    tools: [
      "Shopify",
      "WooCommerce",
      "Facebook Ads",
      "Google Analytics",
      "Klaviyo",
    ],
    skills: [
      "Digital marketing",
      "Product sourcing",
      "Customer service",
      "Analytics",
      "Design",
    ],
    icon: "Star",
    marketSize: "Global e-commerce worth $6.2T+ annually",
    averageIncome: {
      beginner: "$0-2K/month",
      intermediate: "$2K-15K/month",
      advanced: "$15K-100K+/month",
    },
    userStruggles: [
      "Finding profitable products",
      "Driving traffic to store",
      "Managing inventory",
      "Converting visitors to sales",
    ],
    solutions: [
      "Start with validated products",
      "Focus on SEO and content marketing",
      "Use inventory management tools",
      "Optimize conversion funnel",
    ],
    bestFitPersonality: [
      "Entrepreneurial mindset",
      "Detail-oriented",
      "Marketing-focused",
      "Customer-centric",
    ],
    resources: {
      platforms: ["Shopify", "WooCommerce", "BigCommerce", "Etsy"],
      learning: ["E-commerce courses", "Dropshipping guides"],
      tools: ["Shopify", "Facebook Ads", "Google Analytics", "Klaviyo"],
    },
    actionPlan: {
      phase1: [
        "Research product niches",
        "Set up online store",
        "Source initial products",
        "Create product listings",
      ],
      phase2: [
        "Launch marketing campaigns",
        "Optimize store conversion",
        "Build customer base",
        "Expand product line",
      ],
      phase3: [
        "Scale advertising spend",
        "Develop private label products",
        "Build brand loyalty",
        "Explore new markets",
      ],
    },
  },
  {
    id: "youtube-automation",
    name: "YouTube Automation",
    description:
      "Create and monetize YouTube channels with minimal personal involvement",
    detailedDescription:
      "YouTube automation involves creating YouTube channels that generate revenue through systematic content creation, often using outsourced creators, stock footage, or AI tools to minimize personal time investment.",
    fitScore: 0,
    difficulty: "Medium",
    timeToProfit: "3-6 months",
    startupCost: "$500-2K",
    potentialIncome: "$1K-50K+/month",
    pros: [
      "Passive income potential",
      "Scalable to multiple channels",
      "No need to be on camera",
      "Multiple monetization methods",
      "Global audience reach",
      "Long-term asset building",
    ],
    cons: [
      "Algorithm dependency",
      "High competition",
      "Initial investment required",
      "Time to build audience",
      "Content creation challenges",
      "Platform policy changes",
    ],
    tools: ["TubeBuddy", "VidIQ", "Canva", "AI voice tools", "Stock footage"],
    skills: [
      "Video editing",
      "SEO optimization",
      "Market research",
      "Analytics",
      "Outsourcing",
    ],
    icon: "Play",
    marketSize: "YouTube ad revenue over $28B+ annually",
    averageIncome: {
      beginner: "$0-500/month",
      intermediate: "$500-5K/month",
      advanced: "$5K-50K+/month",
    },
    userStruggles: [
      "Finding profitable niches",
      "Creating engaging content",
      "Managing outsourced team",
      "Maintaining consistent uploads",
    ],
    solutions: [
      "Research trending topics",
      "Study successful channels",
      "Use project management tools",
      "Create content calendars",
    ],
    bestFitPersonality: [
      "Business-minded",
      "Patient with long-term goals",
      "Good at delegation",
      "Analytical thinker",
    ],
    resources: {
      platforms: ["YouTube Studio", "TubeBuddy", "VidIQ"],
      learning: ["YouTube automation courses", "Video marketing guides"],
      tools: ["TubeBuddy", "VidIQ", "Canva", "Murf AI"],
    },
    actionPlan: {
      phase1: [
        "Research profitable niches",
        "Create channel and branding",
        "Develop content strategy",
        "Upload first videos",
      ],
      phase2: [
        "Optimize for YouTube SEO",
        "Build outsourcing team",
        "Scale content production",
        "Apply for monetization",
      ],
      phase3: [
        "Launch multiple channels",
        "Diversify revenue streams",
        "Build automation systems",
        "Scale to 6-figure business",
      ],
    },
  },
  {
    id: "local-service",
    name: "Local Service Business",
    description:
      "Provide services to businesses and residents in your local area",
    detailedDescription:
      "Local service businesses provide essential services to nearby businesses and homeowners, such as cleaning, lawn care, handyman services, pet care, or professional services like accounting or consulting.",
    fitScore: 0,
    difficulty: "Easy",
    timeToProfit: "1-4 weeks",
    startupCost: "$100-2K",
    potentialIncome: "$2K-20K/month",
    pros: [
      "Quick to start earning",
      "Recurring customer relationships",
      "Lower competition online",
      "Cash-based transactions",
      "Personal relationships",
      "Essential service demand",
    ],
    cons: [
      "Limited to local market",
      "Physical presence required",
      "Weather/seasonal factors",
      "Equipment and vehicle needs",
      "Time-intensive work",
      "Limited scalability",
    ],
    tools: [
      "Google My Business",
      "Nextdoor",
      "Square",
      "QuickBooks",
      "Scheduling apps",
    ],
    skills: [
      "Service expertise",
      "Customer service",
      "Local marketing",
      "Operations",
      "Reliability",
    ],
    icon: "Target",
    marketSize: "Local services market worth $500B+ in US",
    averageIncome: {
      beginner: "$1K-3K/month",
      intermediate: "$3K-8K/month",
      advanced: "$8K-20K/month",
    },
    userStruggles: [
      "Finding first customers",
      "Pricing services competitively",
      "Managing scheduling",
      "Scaling beyond personal time",
    ],
    solutions: [
      "Start with friends and neighbors",
      "Research local competitor pricing",
      "Use scheduling software",
      "Hire help as you grow",
    ],
    bestFitPersonality: [
      "Enjoys hands-on work",
      "Good with people",
      "Reliable and trustworthy",
      "Community-oriented",
    ],
    resources: {
      platforms: ["Google My Business", "Nextdoor", "TaskRabbit", "Thumbtack"],
      learning: ["Local business guides", "Service industry training"],
      tools: ["Google My Business", "Square", "QuickBooks", "Calendly"],
    },
    actionPlan: {
      phase1: [
        "Define your service offering",
        "Get necessary licenses/insurance",
        "Create Google My Business",
        "Get first customers",
      ],
      phase2: [
        "Build customer reviews",
        "Expand service offerings",
        "Implement booking system",
        "Increase rates gradually",
      ],
      phase3: [
        "Hire additional workers",
        "Expand service area",
        "Add complementary services",
        "Build referral system",
      ],
    },
  },
  {
    id: "high-ticket-sales",
    name: "High-Ticket Sales",
    description:
      "Sell premium products or services with substantial commission potential",
    detailedDescription:
      "High-ticket sales involves selling expensive products or services, typically involving consultative sales processes, relationship building, and substantial per-transaction earnings. This can include real estate, luxury goods, B2B software, or coaching programs.",
    fitScore: 0,
    difficulty: "Hard",
    timeToProfit: "2-6 months",
    startupCost: "$0-1K",
    potentialIncome: "$5K-100K+/month",
    pros: [
      "High earnings per sale",
      "Relationship-based business",
      "Skills transfer to many industries",
      "Performance-based rewards",
      "Professional development",
      "Network building opportunities",
    ],
    cons: [
      "Inconsistent income timing",
      "High rejection rates",
      "Pressure and stress",
      "Long sales cycles",
      "Requires thick skin",
      "Performance accountability",
    ],
    tools: [
      "CRM software",
      "LinkedIn Sales Navigator",
      "Zoom",
      "Email automation",
      "Calendly",
    ],
    skills: [
      "Communication",
      "Relationship building",
      "Negotiation",
      "Psychology",
      "Persistence",
    ],
    icon: "TrendingUp",
    marketSize: "B2B sales market worth $6T+ globally",
    averageIncome: {
      beginner: "$2K-8K/month",
      intermediate: "$8K-25K/month",
      advanced: "$25K-100K+/month",
    },
    userStruggles: [
      "Handling rejection",
      "Building initial pipeline",
      "Closing complex deals",
      "Managing long sales cycles",
    ],
    solutions: [
      "Focus on relationship building",
      "Use consultative selling approach",
      "Track metrics and optimize",
      "Continuous learning and practice",
    ],
    bestFitPersonality: [
      "Excellent communicator",
      "Resilient to rejection",
      "Goal-oriented",
      "Enjoys helping others",
    ],
    resources: {
      platforms: ["LinkedIn", "Salesforce", "HubSpot"],
      learning: ["Sales training courses", "Industry certifications"],
      tools: ["CRM software", "LinkedIn Sales Navigator", "Calendly"],
    },
    actionPlan: {
      phase1: [
        "Choose your industry",
        "Learn product knowledge",
        "Set up CRM system",
        "Start prospecting",
      ],
      phase2: [
        "Build sales pipeline",
        "Refine sales process",
        "Track and optimize metrics",
        "Close first deals",
      ],
      phase3: [
        "Scale prospecting efforts",
        "Build referral network",
        "Mentor other sales reps",
        "Consider leadership roles",
      ],
    },
  },
  {
    id: "saas-development",
    name: "SaaS Development",
    description:
      "Build software applications that generate recurring subscription revenue",
    detailedDescription:
      "SaaS (Software as a Service) development involves creating web applications that solve specific problems for businesses or consumers, generating recurring revenue through subscription models.",
    fitScore: 0,
    difficulty: "Hard",
    timeToProfit: "6-18 months",
    startupCost: "$500-5K",
    potentialIncome: "$1K-500K+/month",
    pros: [
      "Recurring revenue model",
      "Highly scalable business",
      "High profit margins",
      "Global market reach",
      "Valuable asset creation",
      "Solving real problems",
    ],
    cons: [
      "High technical barriers",
      "Long development time",
      "Competitive market",
      "Ongoing maintenance costs",
      "Customer churn challenges",
      "Significant upfront investment",
    ],
    tools: ["AWS", "React", "Node.js", "Stripe", "Analytics tools"],
    skills: [
      "Programming",
      "Product management",
      "UI/UX design",
      "Marketing",
      "Customer support",
    ],
    icon: "Monitor",
    marketSize: "Global SaaS market worth $300B+ annually",
    averageIncome: {
      beginner: "$0-2K/month",
      intermediate: "$2K-25K/month",
      advanced: "$25K-500K+/month",
    },
    userStruggles: [
      "Finding product-market fit",
      "Technical development challenges",
      "Customer acquisition costs",
      "Managing development timeline",
    ],
    solutions: [
      "Start with MVP and iterate",
      "Use no-code tools initially",
      "Focus on customer feedback",
      "Build in public for accountability",
    ],
    bestFitPersonality: [
      "Technical problem solver",
      "Patient with long-term goals",
      "Customer-focused",
      "Enjoys continuous learning",
    ],
    resources: {
      platforms: ["AWS", "Vercel", "Stripe", "Firebase"],
      learning: ["Coding bootcamps", "SaaS development courses"],
      tools: ["React", "Node.js", "PostgreSQL", "Stripe"],
    },
    actionPlan: {
      phase1: [
        "Validate business idea",
        "Learn required technologies",
        "Build MVP version",
        "Get first beta users",
      ],
      phase2: [
        "Implement user feedback",
        "Add payment processing",
        "Focus on user acquisition",
        "Optimize conversion funnel",
      ],
      phase3: [
        "Scale marketing efforts",
        "Add advanced features",
        "Build team as needed",
        "Consider investment/exit",
      ],
    },
  },
  {
    id: "social-media-agency",
    name: "Social Media Marketing Agency",
    description:
      "Help businesses grow their online presence through social media management",
    detailedDescription:
      "Social media marketing agencies provide comprehensive social media services to businesses, including content creation, account management, advertising campaigns, and strategy development across various platforms.",
    fitScore: 0,
    difficulty: "Medium",
    timeToProfit: "1-3 months",
    startupCost: "$500-2K",
    potentialIncome: "$3K-50K+/month",
    pros: [
      "High demand service",
      "Recurring monthly revenue",
      "Creative and strategic work",
      "Scalable business model",
      "Work with diverse clients",
      "Remote work friendly",
    ],
    cons: [
      "Keeping up with algorithm changes",
      "Client management challenges",
      "Competitive market",
      "Proving ROI pressure",
      "Time-intensive content creation",
      "Platform dependency",
    ],
    tools: [
      "Hootsuite",
      "Canva",
      "Facebook Ads Manager",
      "Analytics tools",
      "Scheduling software",
    ],
    skills: [
      "Social media marketing",
      "Content creation",
      "Analytics",
      "Client management",
      "Design",
    ],
    icon: "Users",
    marketSize: "Social media marketing worth $150B+ globally",
    averageIncome: {
      beginner: "$2K-5K/month",
      intermediate: "$5K-15K/month",
      advanced: "$15K-50K+/month",
    },
    userStruggles: [
      "Finding quality clients",
      "Proving measurable results",
      "Managing multiple accounts",
      "Staying current with trends",
    ],
    solutions: [
      "Specialize in specific niches",
      "Create detailed reporting systems",
      "Use management tools",
      "Continuous learning and adaptation",
    ],
    bestFitPersonality: [
      "Creative and strategic",
      "Excellent communicator",
      "Detail-oriented",
      "Adaptable to change",
    ],
    resources: {
      platforms: ["Facebook", "Instagram", "LinkedIn", "TikTok"],
      learning: ["Social media marketing courses", "Platform certifications"],
      tools: ["Hootsuite", "Buffer", "Canva", "Google Analytics"],
    },
    actionPlan: {
      phase1: [
        "Learn social media platforms",
        "Create portfolio content",
        "Get first clients",
        "Set up management tools",
      ],
      phase2: [
        "Develop service packages",
        "Build case studies",
        "Scale client base",
        "Optimize processes",
      ],
      phase3: [
        "Hire team members",
        "Expand service offerings",
        "Build agency brand",
        "Target larger clients",
      ],
    },
  },
  {
    id: "ai-marketing-agency",
    name: "AI Marketing Agency",
    description:
      "Leverage AI tools to provide cutting-edge marketing solutions for businesses",
    detailedDescription:
      "AI marketing agencies use artificial intelligence tools and technologies to provide advanced marketing services, including automated content creation, predictive analytics, chatbots, and AI-powered advertising optimization.",
    fitScore: 0,
    difficulty: "Hard",
    timeToProfit: "2-6 months",
    startupCost: "$1K-5K",
    potentialIncome: "$5K-100K+/month",
    pros: [
      "Cutting-edge technology advantage",
      "High-value service offering",
      "Scalable with automation",
      "Premium pricing potential",
      "Growing market demand",
      "Competitive differentiation",
    ],
    cons: [
      "Steep learning curve",
      "Rapidly changing technology",
      "High client expectations",
      "Technical complexity",
      "Tool subscription costs",
      "Need for continuous learning",
    ],
    tools: [
      "OpenAI API",
      "Claude",
      "Midjourney",
      "Marketing automation platforms",
      "Analytics tools",
    ],
    skills: [
      "AI tool mastery",
      "Marketing strategy",
      "Data analysis",
      "Technical integration",
      "Client education",
    ],
    icon: "Brain",
    marketSize: "AI marketing market projected $100B+ by 2030",
    averageIncome: {
      beginner: "$3K-8K/month",
      intermediate: "$8K-25K/month",
      advanced: "$25K-100K+/month",
    },
    userStruggles: [
      "Keeping up with AI developments",
      "Educating clients on AI value",
      "Integration complexity",
      "Proving AI effectiveness",
    ],
    solutions: [
      "Focus on specific AI tools",
      "Create educational content",
      "Start with simple implementations",
      "Track and share success metrics",
    ],
    bestFitPersonality: [
      "Tech-savvy and innovative",
      "Continuous learner",
      "Strategic thinker",
      "Early adopter mindset",
    ],
    resources: {
      platforms: ["OpenAI", "Anthropic", "Midjourney", "HubSpot"],
      learning: ["AI marketing courses", "Technical documentation"],
      tools: ["OpenAI API", "Marketing automation", "Analytics platforms"],
    },
    actionPlan: {
      phase1: [
        "Master key AI tools",
        "Create AI-powered demos",
        "Educate potential clients",
        "Land first projects",
      ],
      phase2: [
        "Develop service frameworks",
        "Build case studies",
        "Scale AI implementations",
        "Increase pricing",
      ],
      phase3: [
        "Create proprietary AI solutions",
        "Build specialized team",
        "Target enterprise clients",
        "Consider productization",
      ],
    },
  },
  {
    id: "digital-services",
    name: "Digital Services",
    description:
      "Provide specialized digital services like web development, design, or consulting",
    detailedDescription:
      "Digital services encompass a wide range of technology-based services including web development, graphic design, digital marketing, SEO, content writing, and various forms of digital consulting.",
    fitScore: 0,
    difficulty: "Medium",
    timeToProfit: "1-3 months",
    startupCost: "$0-1K",
    potentialIncome: "$2K-30K+/month",
    pros: [
      "High demand for digital skills",
      "Work from anywhere",
      "Diverse service options",
      "Scalable pricing",
      "Build valuable portfolio",
      "Continuous learning opportunities",
    ],
    cons: [
      "High competition",
      "Keeping skills current",
      "Client acquisition challenges",
      "Time-for-money limitation",
      "Scope creep issues",
      "Technology changes rapidly",
    ],
    tools: [
      "Adobe Creative Suite",
      "Figma",
      "WordPress",
      "Google Analytics",
      "Project management tools",
    ],
    skills: [
      "Technical expertise",
      "Design thinking",
      "Client communication",
      "Project management",
      "Marketing",
    ],
    icon: "Monitor",
    marketSize: "Digital services market worth $500B+ globally",
    averageIncome: {
      beginner: "$1K-3K/month",
      intermediate: "$3K-10K/month",
      advanced: "$10K-30K+/month",
    },
    userStruggles: [
      "Standing out in crowded market",
      "Pricing services appropriately",
      "Managing project scope",
      "Finding quality clients",
    ],
    solutions: [
      "Specialize in specific niches",
      "Build strong portfolio",
      "Use clear contracts",
      "Focus on relationship building",
    ],
    bestFitPersonality: [
      "Technical problem solver",
      "Detail-oriented",
      "Client-focused",
      "Adaptable to new technologies",
    ],
    resources: {
      platforms: ["Upwork", "Fiverr", "99designs", "Toptal"],
      learning: ["Online courses", "Technical certifications"],
      tools: ["Adobe CC", "Figma", "VS Code", "Project management software"],
    },
    actionPlan: {
      phase1: [
        "Choose your specialization",
        "Build portfolio projects",
        "Set up business profiles",
        "Get first clients",
      ],
      phase2: [
        "Refine service offerings",
        "Increase rates gradually",
        "Build client testimonials",
        "Expand skill set",
      ],
      phase3: [
        "Develop premium services",
        "Build agency team",
        "Create passive income streams",
        "Focus on high-value clients",
      ],
    },
  },
  {
    id: "investing-trading",
    name: "Investing & Trading",
    description:
      "Generate returns through strategic investment in various financial instruments",
    detailedDescription:
      "Investing and trading involves generating returns through strategic investment in stocks, cryptocurrency, real estate, forex, or other financial instruments using analysis, market timing, and risk management strategies.",
    fitScore: 0,
    difficulty: "Hard",
    timeToProfit: "3-12 months",
    startupCost: "$1K-10K+",
    potentialIncome: "$500-unlimited/month",
    pros: [
      "Potentially unlimited returns",
      "Passive income opportunity",
      "Work from anywhere",
      "Scalable with capital",
      "Market independence",
      "Financial education benefits",
    ],
    cons: [
      "High risk of losses",
      "Requires significant capital",
      "Emotional stress",
      "Market volatility",
      "Steep learning curve",
      "No guaranteed income",
    ],
    tools: [
      "Trading platforms",
      "Charting software",
      "News feeds",
      "Portfolio trackers",
      "Risk management tools",
    ],
    skills: [
      "Market analysis",
      "Risk management",
      "Emotional control",
      "Research",
      "Mathematical thinking",
    ],
    icon: "TrendingUp",
    marketSize: "Global trading volume $6T+ daily",
    averageIncome: {
      beginner: "$0-1K/month (high variance)",
      intermediate: "$1K-5K/month (high variance)",
      advanced: "$5K-unlimited/month (high variance)",
    },
    userStruggles: [
      "Managing emotions and psychology",
      "Risk management",
      "Information overload",
      "Consistency in profits",
    ],
    solutions: [
      "Start with paper trading",
      "Develop strict risk rules",
      "Focus on education first",
      "Use systematic approaches",
    ],
    bestFitPersonality: [
      "Analytical and disciplined",
      "Comfortable with risk",
      "Emotionally stable",
      "Continuous learner",
    ],
    resources: {
      platforms: [
        "Robinhood",
        "E*TRADE",
        "TD Ameritrade",
        "Interactive Brokers",
      ],
      learning: ["Financial education courses", "Market analysis training"],
      tools: [
        "TradingView",
        "Bloomberg Terminal",
        "Portfolio management software",
      ],
    },
    actionPlan: {
      phase1: [
        "Learn market fundamentals",
        "Practice with paper trading",
        "Develop trading strategy",
        "Start with small amounts",
      ],
      phase2: [
        "Refine risk management",
        "Track performance metrics",
        "Gradually increase capital",
        "Diversify strategies",
      ],
      phase3: [
        "Scale successful strategies",
        "Consider alternative investments",
        "Potentially manage others' money",
        "Build investment business",
      ],
    },
  },
  {
    id: "copywriting",
    name: "Copywriting",
    description:
      "Create persuasive written content that drives sales and engagement",
    detailedDescription:
      "Copywriting involves creating persuasive written content for businesses, including sales pages, email campaigns, advertisements, website copy, and marketing materials designed to drive specific actions from readers.",
    fitScore: 0,
    difficulty: "Medium",
    timeToProfit: "1-3 months",
    startupCost: "$0-500",
    potentialIncome: "$2K-25K+/month",
    pros: [
      "High-value skill in demand",
      "Work from anywhere",
      "Results-driven pricing",
      "Multiple industries to serve",
      "Scalable income potential",
      "Creative and strategic work",
    ],
    cons: [
      "Pressure to deliver results",
      "Competitive market",
      "Client education needed",
      "Income can be project-based",
      "Constant need to prove ROI",
      "Writing skills must be excellent",
    ],
    tools: [
      "Google Docs",
      "Grammarly",
      "Hemingway Editor",
      "Research tools",
      "Project management",
    ],
    skills: [
      "Persuasive writing",
      "Psychology",
      "Market research",
      "A/B testing",
      "Client communication",
    ],
    icon: "FileText",
    marketSize: "Content marketing industry worth $400B+ globally",
    averageIncome: {
      beginner: "$1K-3K/month",
      intermediate: "$3K-10K/month",
      advanced: "$10K-25K+/month",
    },
    userStruggles: [
      "Finding clients who value copy",
      "Proving copy effectiveness",
      "Handling revisions and feedback",
      "Pricing work appropriately",
    ],
    solutions: [
      "Focus on results-driven niches",
      "Track and share conversion data",
      "Set clear revision limits",
      "Charge based on value delivered",
    ],
    bestFitPersonality: [
      "Excellent writer",
      "Persuasive communicator",
      "Research-oriented",
      "Results-focused",
    ],
    resources: {
      platforms: ["Upwork", "Contently", "ClearVoice", "ProBlogger"],
      learning: ["Copywriting courses", "Marketing psychology"],
      tools: ["Google Docs", "Grammarly", "CoSchedule Headline Analyzer"],
    },
    actionPlan: {
      phase1: [
        "Learn copywriting fundamentals",
        "Create sample copy portfolio",
        "Join freelance platforms",
        "Get first clients",
      ],
      phase2: [
        "Specialize in profitable niches",
        "Track conversion results",
        "Raise rates based on results",
        "Build case studies",
      ],
      phase3: [
        "Develop premium packages",
        "Build personal brand",
        "Create copywriting courses",
        "Consider agency model",
      ],
    },
  },
  {
    id: "virtual-assistant",
    name: "Virtual Assistant",
    description:
      "Provide remote administrative, technical, or creative support to businesses",
    detailedDescription:
      "Virtual assistants provide remote support services to entrepreneurs and businesses, including administrative tasks, customer service, social media management, content creation, and specialized technical services.",
    fitScore: 0,
    difficulty: "Easy",
    timeToProfit: "1-2 weeks",
    startupCost: "$0-300",
    potentialIncome: "$1K-8K/month",
    pros: [
      "Low barrier to entry",
      "Flexible schedule",
      "Diverse task variety",
      "Learn new business skills",
      "Stable recurring income",
      "Remote work opportunity",
    ],
    cons: [
      "Can be task-intensive",
      "Time zone coordination",
      "Lower hourly rates initially",
      "Client dependency",
      "Administrative workload",
      "Limited growth potential",
    ],
    tools: [
      "Slack",
      "Zoom",
      "Trello",
      "Google Workspace",
      "Time tracking software",
    ],
    skills: [
      "Organization",
      "Communication",
      "Technical proficiency",
      "Problem-solving",
      "Reliability",
    ],
    icon: "Users",
    marketSize: "Virtual assistant market worth $25B+ globally",
    averageIncome: {
      beginner: "$800-2K/month",
      intermediate: "$2K-5K/month",
      advanced: "$5K-8K/month",
    },
    userStruggles: [
      "Finding quality clients",
      "Setting boundaries",
      "Managing multiple clients",
      "Increasing rates over time",
    ],
    solutions: [
      "Specialize in valuable skills",
      "Set clear work agreements",
      "Use project management tools",
      "Focus on results and value",
    ],
    bestFitPersonality: [
      "Highly organized",
      "Detail-oriented",
      "Reliable and trustworthy",
      "Adaptable to different needs",
    ],
    resources: {
      platforms: ["Belay", "Time Etc", "Fancy Hands", "Upwork"],
      learning: ["VA training courses", "Business skills development"],
      tools: ["Google Workspace", "Slack", "Asana", "Calendly"],
    },
    actionPlan: {
      phase1: [
        "Identify your skill strengths",
        "Create professional profiles",
        "Apply to VA platforms",
        "Get first clients",
      ],
      phase2: [
        "Deliver exceptional service",
        "Build client testimonials",
        "Specialize in high-value tasks",
        "Increase hourly rates",
      ],
      phase3: [
        "Build VA agency",
        "Hire other VAs",
        "Create specialized services",
        "Focus on premium clients",
      ],
    },
  },
  {
    id: "online-reselling",
    name: "Online Reselling",
    description:
      "Buy and resell products online for profit through arbitrage opportunities",
    detailedDescription:
      "Online reselling involves purchasing products at low prices and reselling them at higher prices through online marketplaces. This can include retail arbitrage, wholesale purchasing, thrift store finds, clearance items, or sourcing from manufacturers.",
    fitScore: 0,
    difficulty: "Easy",
    timeToProfit: "1-4 weeks",
    startupCost: "$200-2K",
    potentialIncome: "$1K-15K+/month",
    pros: [
      "Low barrier to entry",
      "Quick cash flow potential",
      "Learn market dynamics",
      "Flexible schedule",
      "Scalable business model",
      "No specialized skills required",
    ],
    cons: [
      "Time-intensive sourcing",
      "Storage space requirements",
      "Competition pressure",
      "Seasonal demand variations",
      "Platform fee costs",
      "Inventory management challenges",
    ],
    tools: [
      "Amazon Seller App",
      "eBay",
      "Facebook Marketplace",
      "Keepa",
      "Inventory management software",
    ],
    skills: [
      "Product research",
      "Market analysis",
      "Negotiation",
      "Customer service",
      "Inventory management",
    ],
    icon: "Star",
    marketSize: "Online resale market worth $200B+ globally",
    averageIncome: {
      beginner: "$500-2K/month",
      intermediate: "$2K-8K/month",
      advanced: "$8K-15K+/month",
    },
    userStruggles: [
      "Finding profitable products",
      "Managing storage space",
      "Dealing with returns",
      "Time-intensive sourcing",
    ],
    solutions: [
      "Use product research tools",
      "Start with online arbitrage",
      "Optimize return policies",
      "Automate where possible",
    ],
    bestFitPersonality: [
      "Enjoys hunting for deals",
      "Detail-oriented",
      "Comfortable with risk",
      "Good at pattern recognition",
    ],
    resources: {
      platforms: ["Amazon FBA", "eBay", "Poshmark", "Mercari"],
      learning: ["Reselling courses", "Arbitrage communities"],
      tools: ["Keepa", "CamelCamelCamel", "Amazon Seller App"],
    },
    actionPlan: {
      phase1: [
        "Learn product research",
        "Start with small investments",
        "Test different product categories",
        "Set up selling accounts",
      ],
      phase2: [
        "Scale successful products",
        "Optimize sourcing process",
        "Build inventory systems",
        "Expand to new platforms",
      ],
      phase3: [
        "Consider wholesale relationships",
        "Automate operations",
        "Build team for sourcing",
        "Explore private labeling",
      ],
    },
  },
  {
    id: "handmade-goods",
    name: "Handmade Goods",
    description:
      "Create and sell handcrafted products through online marketplaces",
    detailedDescription:
      "Handmade goods businesses involve creating unique, handcrafted products and selling them through online platforms. This can include jewelry, clothing, home decor, art, crafts, or any custom-made items that showcase personal creativity and skill.",
    fitScore: 0,
    difficulty: "Easy",
    timeToProfit: "2-8 weeks",
    startupCost: "$100-1K",
    potentialIncome: "$500-10K+/month",
    pros: [
      "Creative fulfillment",
      "Unique product offerings",
      "Personal brand building",
      "Flexible production schedule",
      "Premium pricing potential",
      "Direct customer relationships",
    ],
    cons: [
      "Time-intensive production",
      "Limited scalability",
      "Material cost fluctuations",
      "Seasonal demand patterns",
      "Photography and marketing needs",
      "Competition from mass production",
    ],
    tools: [
      "Etsy",
      "Shopify",
      "Canva",
      "Social media platforms",
      "Photography equipment",
    ],
    skills: [
      "Crafting expertise",
      "Photography",
      "Product design",
      "Customer service",
      "Social media marketing",
    ],
    icon: "Star",
    marketSize: "Handmade goods market worth $44B+ globally",
    averageIncome: {
      beginner: "$200-1K/month",
      intermediate: "$1K-4K/month",
      advanced: "$4K-10K+/month",
    },
    userStruggles: [
      "Pricing products appropriately",
      "Standing out in crowded market",
      "Scaling production",
      "Managing custom orders",
    ],
    solutions: [
      "Calculate true cost including time",
      "Focus on unique value proposition",
      "Streamline production processes",
      "Set clear custom order policies",
    ],
    bestFitPersonality: [
      "Creative and artistic",
      "Detail-oriented",
      "Patient with production",
      "Enjoys working with hands",
    ],
    resources: {
      platforms: [
        "Etsy",
        "Amazon Handmade",
        "Facebook Marketplace",
        "Local craft fairs",
      ],
      learning: ["Crafting tutorials", "Etsy seller guides"],
      tools: ["Etsy", "Canva", "Instagram", "Photography lighting"],
    },
    actionPlan: {
      phase1: [
        "Perfect your craft",
        "Create initial product line",
        "Set up online store",
        "Take quality product photos",
      ],
      phase2: [
        "Build social media presence",
        "Gather customer feedback",
        "Expand product offerings",
        "Optimize pricing strategy",
      ],
      phase3: [
        "Scale production methods",
        "Consider wholesale opportunities",
        "Build brand loyalty",
        "Explore custom order services",
      ],
    },
  },
];
